# GitHub Pages Configuration
theme: jekyll-theme-cayman
title: CatechHub
description: Il tuo registro di catechismo sempre con te
url: "https://catechhub-dev.github.io/CatechHub"
baseurl: "/CatechHub"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
